#! /opt/pwn.college/python

import argparse

binary_name = "elf-crackme-level1.0"

if __name__ == '__main__':
    
    print("This python script is used to modify binary file -", binary_name)

    parser = argparse.ArgumentParser()
    parser.add_argument('-o', "--offset", help="Please provide the offset to the target binary", type=str, required=True)
    parser.add_argument('-v', "--value", help="Please provide the value written to the target binary", type=str, required=True)
    args = parser.parse_args()

    offset = int(args.offset, 0)
    value = int(args.value, 0)

    with open(binary_name, "r+b") as fd:
        fd.seek(offset)
        fd.write(value)
